name: CI-CD
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  # .yarnrc.yml needs this
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_PASSWORD: postgres
        # health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install and build
        run: yarn install && yarn build

      - name: unit test
        run: yarn test --coverage
        env:
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_DATABASE: postgres

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  cd:
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      max-parallel: 1 # to avoid git conflicts
      matrix:
        lib:
          - eventually
          - eventually-pg
          - eventually-express
          - eventually-broker

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: analyze ${{ matrix.lib }}
        id: analyze
        uses: rotorsoft/semrel-analyze@v2
        with:
          package: "@andela-technology/${{ matrix.lib }}"
          directory: "libs/${{ matrix.lib }}"

      - name: analysis
        run: |
          echo "last-tag: ${{ steps.analyze.outputs.last-tag }}"
          echo "next-tag: ${{ steps.analyze.outputs.next-tag }}"
          echo "next-version: ${{ steps.analyze.outputs.next-version }}"
          echo "${{ steps.analyze.outputs.change-log }}"

      # Perform the release of the package.
      #
      # The release consist of the following steps:
      #
      #   * Install dependencies and build
      #   * Generate the changelog
      #   * Bump version to the next semver version updating package.json
      #   * Do a commit
      #   * Tag with semver version and push
      #   * Create a release in github
      #   * Publish npm package on github registry
      #
      # Note: This release process uses tags to determine next version.
      # In case of trouble, check the tags and the package name in package.json match.
      #
      - name: Release ${{ matrix.lib }}
        id: release
        uses: rotorsoft/semrel-release@v2
        with:
          github-token: "${{ secrets.ACTIONS_TOKEN }}"
          npm-token: "${{ secrets.NPM_TOKEN }}"
          npm-registry: "npm.pkg.github.com"
          npm-access: "restricted"
          user: "andela"
          email: "devops@andela.com"
          package: "@andela-technology/${{ matrix.lib }}"
          directory: "libs/${{ matrix.lib }}"
          tag: "${{ steps.analyze.outputs.next-tag }}"
          version: "${{ steps.analyze.outputs.next-version }}"
          change-log: "${{ steps.analyze.outputs.change-log }}"